name: flutter_pomodoro_timer
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.1+1

  cupertino_icons: ^0.1.2
  flutter_bloc: ^7.3.3
  table_calendar: ^3.0.3
  flutter_material_pickers: ^3.1.2
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
